#!/usr/bin/env bash

if [ -z "$CLANG_FORMAT" ]; then
  CLANG_FORMAT="clang-format"
fi

for f in $(ls src/*.cc src/*.h); do
  if ! diff -U 1 <($CLANG_FORMAT $f) $f; then
    echo
    echo "!!!!!!"
    echo "!! Failed clang-format check, please run 'clang-format -i src/*.cc src/*.h'" 1>&2
    echo "!!!!!!"
    exit 1
  fi
done
